//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticaFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lineapedido
    {
        public int id { get; set; }
        public int idPedido { get; set; }
        public int idCoche { get; set; }
        public double precioCoche { get; set; }
    }
}
