//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticaFinal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class cochesdawEntities2 : DbContext
    {
        public cochesdawEntities2()
            : base("name=cochesdawEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<coche> coche { get; set; }
        public virtual DbSet<lineapedido> lineapedido { get; set; }
        public virtual DbSet<pedido> pedido { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
        public virtual DbSet<stock> stock { get; set; }
    }
}
