//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticaFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stock
    {
        public int idCoche { get; set; }
        public int unidades { get; set; }
    
        public virtual coche coche { get; set; }
    }
}
